//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp
    {
        public string dispatchId { get; set; }
        public string roomId { get; set; }
        public string roomName { get; set; }
        public Nullable<System.DateTime> checkDate { get; set; }
        public string inspectorId1 { get; set; }
        public string inspectorCode1 { get; set; }
        public string inspectorName1 { get; set; }
        public string inspectorId2 { get; set; }
        public string itemId { get; set; }
        public string itemName { get; set; }
    }
}
